name: Deploy to Edgeserver.io

on:
  push:
    branches:
      - "master"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.11.0"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - name: Build
        run: yarn build
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@master
        with:
          app_id: "987654321"
          server: https://api.edgeserver.io
          token: ${{ secrets.SIGNAL_TOKEN }}
          directory: dist
      - name: Edgeserver Staging Upload
        uses: lvkdotsh/edgeserver-action@v0.1.1
        with:
          app_id: "66656824585097216"
          server: https://api.edgeserver.dev
          token: ${{ secrets.SIGNAL_TOKEN2 }}
          directory: dist
